version: 0.2

phases:
  pre_build:
    commands:
      - echo "Login to ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com
      - mvn clean package -DskipTests
  build:
      commands:
        - cd my-maven-docker-project
        - mvn clean install

  post_build:
      commands:
        - echo "Build completed. Listing output directory..."
        - ls -R target/
        - docker build -t $IMAGE_REPO_NAME: $IMAGE_TAG .
        - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
        - docker images
        - echo "Pushing the Docker image..."
        - docker push $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
        - echo "Docker image pushed to ECR Successfully"

  artifacts:
    files:
      - 'my-maven-docker-project/target/*.jar'
    discard-paths: yes